name-template: 'v$NEXT_VERSION ğŸŒˆ'
tag-template: 'v$NEXT_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - feature
      - enhancement
  - title: 'ğŸ› Bug Fixes'
    labels:
      - fix
      - bugfix
      - bug
  - title: 'ğŸ§° Maintenance'
    labels:
      - chore
      - maintenance
      - ci
      - dependencies
  - title: 'ğŸ“š Documentation'
    labels:
      - documentation
      - docs
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bugfix
      - bug
      - chore
      - maintenance
      - ci
      - dependencies
      - documentation
      - docs
  default: patch
template: |
  ## Changes

  $CHANGES
